---
- name: Download atom editor
  get_url: url="https://aur.archlinux.org/cgit/aur.git/snapshot/atom-editor.tar.gz"
           dest="/aur/atom-editor.tar.gz"
  tags:
    - programs

- name: Unarchive atom editor
  unarchive: src="/aur/atom-editor.tar.gz"
             dest="/aur"
             copy=no
  tags:
    - programs

- name: Install atom editor
  command: makepkg -sri
           chdir="/aur/atom-editor"
