---
- name: Install "Xorg"
  pacman: name="{{ item }}"
          state=present
  with_items:
    - xorg-server
  tags:
    - graphics

- name: Install graphics drivers
  pacman: name="{{ item }}"
          state=present
  with_items: "{{ graphics_driver_packages }}"
  tags:
    - graphics

- name: Install input drivers
  pacman: name="{{ item }}"
          state=present
  with_items: "{{ input_drivers }}"
  tags:
    - graphics

- name: Install Gnome Display Manager
  pacman: name=gdm
          state=present
  tags:
    - graphics

- name: Enable gdm module
  command: systemctl enable gdm
  tags:
    - graphics

- name: Install i3
  pacman: name={{ item }}
          state=present
  with_items:
    - "i3"
    - "dmenu"
  tags:
    - graphics

- name: Install terminal emulator "{{ terminal_emulator }}"
  pacman: name="{{ terminal_emulator }}"
          state=present
  tags:
    - graphics

- name: Copy i3 conf
  template: src=i3.conf.j2
            dest=/home/{{ username }}/.i3/config
            owner="{{ username }}"
            group="{{ username }}"
  tags:
    - graphics

- name: Create i3status conf directory
  file: path=/home/{{ username }}/.config/i3status
        state=directory
  tags:
    - graphics

- name: Copy i3status conf
  copy: src=i3status.conf
        dest=/home/{{ username }}/.config/i3status/config
  tags:
    - graphics

- name: Copy wallpaper
  copy: src=wallpaper.png
        dest=/home/{{ username }}/.i3/wallpaper.png
  tags:
    - graphics
