---
- name: Update pacman
  pacman: update_cache=yes
  tags:
    - system

- name: Upgrade with pacman
  pacman: upgrade=yes
  tags:
    - system

- name: Install base-devel (for AUR, etc.)
  pacman: name=base-devel
          state=present
  tags:
    - system

- include: users.yml
- include: graphics.yml
- include: programs.yml
